;METADATA=(Diff=true, UseCommands=true)
[/Script/GMP.GMPMeta]
+MessageTagsList=(Tag="GameState",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GameState.OnPostStartPlay",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GMP",Parameters=("Actor","HitResult"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.DeselectZombie",Parameters=,ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnInteractionClicked",Parameters=("Actor","HitResult"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnPlayerPossessed",Parameters=("Pawn"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnPostWorldCleanup",Parameters=("World","bool","bool"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnPostWorldInitialization",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnPreWorldInitialization",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnStorageItemClicked",Parameters=("UserWidget"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnStorageUpdated",Parameters=("Actor"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnWorldBeginPlay",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnWorldBeginPlayNextTick",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnWorldBeginTearDown",Parameters=("World"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnWorldCleanup",Parameters=("World","bool","bool"),ResponseTypes=)
+MessageTagsList=(Tag="GMP.OnWorldInitializedActors",Parameters=("World"),ResponseTypes=)
+GMPTagFileList=Config/DefaultMessageTags.ini

